# Generated by Django 5.2 on 2026-04-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_course_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
