# Generated by Django 5.2 on 2026-04-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_project_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group_number',
            field=models.IntegerField(blank=True, help_text='Número de grupo auto-asignado por proyecto grupal', null=True),
        ),
    ]
