# Generated by Django 5.2 on 2026-04-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_project_group_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
