# Generated by Django 5.2 on 2026-05-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_student_visibility_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='activity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
