# Generated by Django 5.2 on 2026-06-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_add_activity_date_to_coursetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
