# Generated by Django 5.2 on 2026-08-05 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_single_active_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='period',
        ),
    ]
