# Generated by Django 5.2 on 2026-08-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_move_evaluation_template_to_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='heading_color_dark',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='heading_color_light',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='palette',
            field=models.CharField(choices=[('dark', 'Oscuro'), ('light', 'Claro')], default='dark', max_length=10),
        ),
        migrations.AddField(
            model_name='presentation',
            name='subheading_color_dark',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='presentation',
            name='subheading_color_light',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='theme',
            field=models.CharField(choices=[('quarto', 'Quarto')], default='quarto', max_length=50),
        ),
    ]
