# Generated by Django 5.2 on 2026-08-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_presentations_to_quarto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='theme',
            field=models.CharField(choices=[('quarto', 'Quarto'), ('serif', 'Serif'), ('ocean', 'Océano'), ('contrast', 'Alto contraste')], default='quarto', max_length=50),
        ),
    ]
