# Generated by Django 5.2 on 2026-06-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0009_user_active_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ci_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
