# Generated by Django 5.2 on 2026-08-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0010_ci_number_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
